### ISSUE TITLE
AuthenticationSuccessHandler can be deprecated

### ISSUE THREAD

**Issue by richardhj** [ConnectHolland/secure-jwt-bundle#20]
The `AuthenticationSuccessHandler` that solely sets the cookie can be deprecated. The lexik/jwt-bundle since version 2.7 can set cookies itself. 

This is the config:
```yml
lexik_jwt_authentication:
  token_extractors:
    cookie:
      enabled: true
      name: BEARER
  # add these lines:
  set_cookies:
    BEARER: ~
```

So I think it is safe to NOT use your authentication listener but the default lexik's one when updating the config. You may want to update the README :)
